name: Health Reminder Cron

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  trigger-health-reminders:
    name: Trigger Health Reminders
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Health Reminder API
        id: trigger_reminders
        run: |
          echo "Triggering health reminders at $(date)"
          
          # Make API call to trigger reminders
          response=$(curl -s -w "%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.HEALTH_REMINDER_CRON_SECRET }}" \
            -d '{"source": "github_actions", "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}' \
            "${{ vars.APP_URL }}/api/health/reminders/trigger")
          
          # Extract HTTP status code (last 3 characters)
          http_code="${response: -3}"
          response_body="${response%???}"
          
          echo "HTTP Status: $http_code"
          echo "Response: $response_body"
          
          # Check if request was successful
          if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
            echo "✅ Health reminders triggered successfully"
            echo "status=success" >> $GITHUB_OUTPUT
            echo "response=$response_body" >> $GITHUB_OUTPUT
          else
            echo "❌ Failed to trigger health reminders"
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "error_code=$http_code" >> $GITHUB_OUTPUT
            echo "error_response=$response_body" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Log Success
        if: steps.trigger_reminders.outputs.status == 'success'
        run: |
          echo "Health reminder job completed successfully"
          echo "Response: ${{ steps.trigger_reminders.outputs.response }}"

      - name: Handle Failure
        if: failure()
        run: |
          echo "Health reminder job failed"
          echo "Error Code: ${{ steps.trigger_reminders.outputs.error_code }}"
          echo "Error Response: ${{ steps.trigger_reminders.outputs.error_response }}"
          
          # Log failure details for debugging
          echo "Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Repository: ${{ github.repository }}"

      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issue_body = `
            ## 🚨 Health Reminder Cron Job Failed
            
            **Workflow:** ${{ github.workflow }}
            **Run ID:** ${{ github.run_id }}
            **Timestamp:** ${new Date().toISOString()}
            **Error Code:** ${{ steps.trigger_reminders.outputs.error_code }}
            
            **Error Details:**
            \`\`\`
            ${{ steps.trigger_reminders.outputs.error_response }}
            \`\`\`
            
            **Troubleshooting Steps:**
            1. Check if the application is running and accessible
            2. Verify the HEALTH_REMINDER_CRON_SECRET is correctly configured
            3. Ensure the APP_URL environment variable is set correctly
            4. Check application logs for any errors
            5. Verify the /api/health/reminders/trigger endpoint is working
            
            **Links:**
            - [Failed Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            - [Application URL](${{ vars.APP_URL }})
            `;
            
            // Create an issue for the failure (optional - remove if not desired)
            // github.rest.issues.create({
            //   owner: context.repo.owner,
            //   repo: context.repo.repo,
            //   title: `Health Reminder Cron Failed - ${new Date().toISOString()}`,
            //   body: issue_body,
            //   labels: ['bug', 'health-management', 'cron-failure']
            // });
            
            console.log('Health reminder cron job failure logged');

  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    if: always()
    needs: [trigger-health-reminders]
    
    steps:
      - name: Check Application Health
        run: |
          echo "Performing application health check"
          
          # Basic health check to ensure app is responsive
          health_response=$(curl -s -w "%{http_code}" \
            -X GET \
            "${{ vars.APP_URL }}/api/health" || echo "000")
          
          http_code="${health_response: -3}"
          
          if [ "$http_code" -eq 200 ]; then
            echo "✅ Application health check passed"
          else
            echo "⚠️ Application health check failed with status: $http_code"
            echo "This may indicate application issues affecting reminder delivery"
          fi

      - name: Log Workflow Summary
        run: |
          echo "=== Health Reminder Cron Summary ==="
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          echo "Trigger Job Status: ${{ needs.trigger-health-reminders.result }}"
          echo "Repository: ${{ github.repository }}"
          echo "=================================="